# Generated by Django 3.2 on 2021-04-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210422_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal',
            old_name='token',
            new_name='name',
        ),
    ]
