# Generated by Django 3.2 on 2021-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Terminal',
        ),
    ]
