# Generated by Django 3.2 on 2021-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210424_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
