# Generated by Django 3.2 on 2021-05-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
