# Generated by Django 3.2 on 2021-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210507_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dept',
        ),
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.ManyToManyField(to='main.Department'),
        ),
    ]
