# Generated by Django 3.2 on 2021-06-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210507_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.CharField(default='MANILA', max_length=8),
            preserve_default=False,
        ),
    ]
